### ISSUE TITLE
Test on windows environment

### ISSUE THREAD

**Issue by milhidaka** [mil-tokyo/webdnn#270]
Check if python part works on windows + python

**Comment by cprogrammer1994** [comment]
Write down the steps, I can test on windows.

**Comment by milhidaka** [comment]
Thanks for the cooperation. However, when I wrote the document, I verified it on my windows environment simultaneously. The document was pushed to dev branch.
https://github.com/mil-tokyo/webdnn/blob/dev/docs/source/tutorial/setup_windows.md
