### ISSUE TITLE
Pytorch Support

### ISSUE THREAD

**Issue by LukasMosser** [mil-tokyo/webdnn#278]
Will there be pytorch support or is it planned?

**Comment by Kiikurage** [comment]
Thank you for your interest. Torch and pytorch are one of the most popular neural network framework, and I think WebDNN should support them. Now we are implementing. Please give us some time.

Also I think it's impossible to support all neural network frameworks, so we're also preparing documents about how to implement custom transpiler frontend (converter which convert model from some neural network framework to WebDNN IR format).

**Comment by Kiikurage** [comment]
I add PyTorch support. Note that this feature uses Open Neural Network Exchange (ONNX) format, and the feature to export pytorch model into ONNX format has not been shipped in PyTorch release version yet. So if you want to compile pytorch model in WebDNN, now, you have to compile pytorch from source by yourself.

https://mil-tokyo.github.io/webdnn/docs/tutorial/pytorch.html

**Comment by LukasMosser** [comment]
Great! Thanks for alerting me to this!
