### ISSUE TITLE
infinite loop for camera confirmation

### ISSUE THREAD

**Issue by milhidaka** [mil-tokyo/webdnn#288]
When neural style transfer demo with webcam video, Safari TP 32 asks security permission. However, if the user presses Allow button, the dialog appears infinitely.
![2017-06-09 10 22 08](https://user-images.githubusercontent.com/9245788/26957097-9f13223e-4cfd-11e7-8c49-81853e658370.png)

**Comment by Kiikurage** [comment]
done
