### ISSUE TITLE
Error generating output graph with keras Resnet Example

### ISSUE THREAD

**Issue by nikhilaravi** [mil-tokyo/webdnn#297]
When I run the command to generate the graph from Resnet example (`python bin/convert_keras.py resnet50.h5 --input_shape '(1,224,224,3)' --out output`) I get the following error:

<img width="717" alt="screen shot 2017-06-15 at 17 52 24" src="https://user-images.githubusercontent.com/5912647/27192520-93626288-51f3-11e7-9315-86f49f5d4352.png">

Can you help me resolve this error?

**Comment by Kiikurage** [comment]
As deafault, webgpu backend validates generated kernel source code

**Comment by Kiikurage** [comment]
As deafault, webgpu backend validates generated kernel source code by using metal compiler. It looks the compiler is not installed. Please set `VALIDATE_GENERATED_SOURCE=0` environment variable flag like follows.

```bash
VALIDATE_GENERATED_SOURCE=0 python bin/convert_keras.py resnet50.h5 --input_shape '(1,224,224,3)' --out output
```

**Comment by nikhilaravi** [comment]
@Kiikurage ah okay thanks that worked! Now I have a different error due to 'em++'. I followed all the  installation instructions as set out in the documentation. 

<img width="1440" alt="screen shot 2017-06-15 at 18 03 08" src="https://user-images.githubusercontent.com/5912647/27192936-096d4de8-51f5-11e7-820c-1201cf935578.png">

**Comment by Kiikurage** [comment]
To ensure the emscripten compiler is installed correctly, could you run compile command in terminal like follows?

```shell
em++ output/kernels_webassembly.cpp -O3 -std=c++11 -s "EXPORTED_FUNCTIONS=['_run', '_init', '_get_weight_buffer', '_get_data_buffer']" -s "WASM=1" -s "TOTAL_MEMORY=134217728" --pre-js //anaconda/envs/python3/lib/python3.6/site-packages/webdnn-1.0.0-py3.6.egg/webdnn/backend/webassembly/webassembly_header.js -o output/kernels_webassembly.js
```

**Comment by nikhilaravi** [comment]
Yes sure I tried running this command and got the following error:
<img width="826" alt="screen shot 2017-06-15 at 18 13 58" src="https://user-images.githubusercontent.com/5912647/27193375-7f77cb70-51f6-11e7-83ec-b39221228282.png">

**Comment by Kiikurage** [comment]
Hmmm... It may be due to the compiler version of emscripten. Please wait for a couple of days to try a little more research.

**Comment by nikhilaravi** [comment]
@Kiikurage okay thanks very much! I'll wait for your response

**Comment by Kiikurage** [comment]
Sorry for late reply.

I couldn't reproduce the same error.
I installed emsdk following [this guide](http://webassembly.org/getting-started/developers-guide/). The installed emsdk version is [33694ce1563aa092acb0d75d936c2b88bb50a609](https://github.com/juj/emsdk/tree/33694ce1563aa092acb0d75d936c2b88bb50a609), and it works.

Please tell me which commit of emsdk you used, and try to install same version of emsdk like follows:

```bash
$ git clone https://github.com/juj/emsdk.git
$ cd emsdk

$ git reset --hard 33694ce1563aa092acb0d75d936c2b88bb50a609

$ ./emsdk install sdk-incoming-64bit binaryen-master-64bit
$ ./emsdk activate sdk-incoming-64bit binaryen-master-64bit
```
