### ISSUE TITLE
NotImplementedError: Unknown activation sigmoid

### ISSUE THREAD

**Issue by hsabouri** [mil-tokyo/webdnn#309]
Hi! When I try to use convert_keras with my own .h5 files it rises the following error : 

![capture du 2017-06-22 15 16 59](https://user-images.githubusercontent.com/12979012/27436085-6bd9254c-575e-11e7-9e37-50f8065932aa.png)

Python version : 3.6.1
Can you help me with this error ? Thank you a lot.

**Comment by Kiikurage** [comment]
Thank you for your intesest. In v1.0.0, only few operators are implemented and sigmoid was postponed to next release.  We plan to release next version in this month and we are working hard now. Please give us some time.

Also, in next release, we plan to update the document about how to implement custom operator by yourself.

**Comment by Kiikurage** [comment]
Hi, 
we released v1.1.0 yesterday. Many activations including sigmoid are supported in this version.　Please use it if you like.
