### ISSUE TITLE
Chainer reshape function AssertionError

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#364]
Hi, 
I try to reshape a `(1, 16384)` variable `h` by using `F.reshape(h, (1, 1024, 4, 4))`.
But I get 
`File "/Users/aixile/anaconda3/envs/snakes/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webassembly/kernels/reshape.py", line 33, in reshape
    assert y.variable.order == op.parameters["out_order"]
AssertionError
`

The `y` is `<Variable v18 shape=[1, 4, 4, 1024], order="NHWC">` and the `op.parameters` is `{'in_order': NC, 'out_order': NCHW, 'out_shape': [1, 1024, 4, 4]}`

**Comment by Kiikurage** [comment]
Sorry for late reply. It looks optimizer's bug.  Please retry transpiling with environment variable `OPTIMIZE=0` to suppress optimization. 

Also if you could, please give us transpiler log. With environment variable `DEBUG=1`, transpiler dumps verbose log.

**Comment by Aixile** [comment]
I try to set the environment variable but still get AssertionError.
I write a sample script to reproduce this Error
https://gist.github.com/Aixile/83902284a32402a6d6442e74abc913d7

tested on chainer==1.24.0

**Comment by milhidaka** [comment]
I found this is due to different data representation order in Chainer (n, c, h, w) and WebDNN (n, h, w, c).
We are planning to solve the situation in #390 , so please wait for a moment.

**Comment by Aixile** [comment]
Thank you! Now, I am able to compile the model successfully.
