### ISSUE TITLE
SyntaxError: invalid syntax, when using webdnn library.

### ISSUE THREAD

**Issue by KentoW** [mil-tokyo/webdnn#379]
日本語で申し訳ありません、
ubuntuでconvert_keras.pyを使用した際、
`  File "./bin/convert_keras.py", line 45
    console.stderr(f"[{path.basename(__file__)}] Generating feedforward graph")
SyntaxError: invalid syntax`
となります。
文字エンコード周りか、webdnnのconsole周りかはわかりませんが、対応願いますでしょうか？

※ issueとは関係ありませんが、対応しているkerasのバージョンは何でしょうか？

**Comment by milhidaka** [comment]
この文はpython 3.6のf-stringという機能を使用しており、それより古いバージョンのpythonを利用しているために出たエラーかと思われます。
python 3.6のご利用をお願いいたします。
kerasはバージョン2.0を想定して開発しております。

**Comment by KentoW** [comment]
迅速な対応ありがとうございます
