### ISSUE TITLE
About input_shape of convert_keras.py

### ISSUE THREAD

**Issue by KentoW** [mil-tokyo/webdnn#380]
As shown in the figure, what should be input to the `input_shape` of `conveet_keras.py` when there are two inputs of keras?
![Keras Model](https://s3.amazonaws.com/keras.io/img/multi-input-multi-output-graph.png)

**Comment by milhidaka** [comment]
Currently, convert_keras.py supports only 1 input variable.
However, multiple input variables can be supported by modifying the code of creating `input_shapes` variable.
https://github.com/mil-tokyo/webdnn/blob/99faf9b634306a42cf124363e41af369e5db76ad/bin/convert_keras.py#50

We will update the code to accept multiple input variables in several days.

**Comment by Kiikurage** [comment]
FYI, not only CLI, you can also convert your model by using `KerasConverter` in your python script. In this case, `input_shape` is not need.

```python
#example.py

import keras
from webdnn.frontend.keras import KerasConverter
from webdnn.backend.webassembly.generator import WebassemblyDescriptorGenerator

model = keras.models.load_model(your_model_path)
graph = KerasConverter(batch_size=1).convert(model)

WebassemblyDescriptorGenerator.generate(graph).save(output_path)
```

**Comment by milhidaka** [comment]
Now, the argument '--input_shape' can be specified multiple times to support multiple input variables.
The patch was just merged to master.
If you still have problems, please reopen the issue.
