### ISSUE TITLE
Isn't WebDNN.prepareAll implemented yet?

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#386]
webdnn.jsを読み込んで、WebDNNを見たのですが、ドキュメントに記載されているprepareAllメソッドがありませんでした。
まだ未実装ですか？

**Comment by milhidaka** [comment]
WebDNN.prepareAll() is replaced by WebDNN.init() in WebDNN 1.1.
See toppage example https://github.com/mil-tokyo/webdnn
Sorry for late document update.

申し訳ございません。WebDNN 1.1にてWebDNN.init()メソッドに変更となりました。
トップページ https://github.com/mil-tokyo/webdnn が最新の使用例となります。
ドキュメントページの更新が遅れておりますが、最新の内容を近日中に反映したいと考えております。

**Comment by y-ich** [comment]
WebDNN.load()ですね。
おかげさまで動きました。ありがとうございました。
