### ISSUE TITLE
Examples does not work well in iPhone

### ISSUE THREAD

**Issue by milhidaka** [mil-tokyo/webdnn#409]
- Layout is disrupted on portrait view (on both ResNet, style transfer)
- Cannot take photo to use
  - In ResNet, clicking "use photo" after taking photo crushes safari.
  - In style transfer, selecting "webcam photo" and taking photo and clicking Run, gives no response.

on iPhone SE, iOS 10.3.2

**Comment by Kiikurage** [comment]
fixed
