### ISSUE TITLE
Add document about compiling descriptor_runner

### ISSUE THREAD

**Issue by zhangjk95** [mil-tokyo/webdnn#444]
Please add some document about how to compile the `descriptor_runner`, such as the prerequisites(like tsc or anything else?), and the compiling command (including the options to compile to single file and the options to make it compatible with EcmaScript5). Thanks!

**Comment by milhidaka** [comment]
In current project structure,
```
npm install
npm run build
```
on the project root directory should be enough to create `dist/webdnn.js` and `dist/webdnn.es5.js`.

Sorry for it is not presented at documentation, and will be added.

**Comment by zhangjk95** [comment]
Thanks!
