### ISSUE TITLE
Lost compatibility with ES5

### ISSUE THREAD

**Issue by zhangjk95** [mil-tokyo/webdnn#465]
The compatibility with EcmaScript5 is lost since https://github.com/mil-tokyo/webdnn/commit/d7594db81edb61b85a20bb0745df7c835f0c01b7 . The current version of `webdnn.es5.js` has generator functions that are not supported by some legacy browsers.
![image](https://user-images.githubusercontent.com/4890396/29649219-ca25ed64-8860-11e7-9dcf-7ca87a185579.png)

**Comment by Kiikurage** [comment]
Sorry, it was fixed.

**Comment by zhangjk95** [comment]
Thank you for fixing it so quickly!
