### ISSUE TITLE
reinforcement learning?

### ISSUE THREAD

**Issue by tycho01** [mil-tokyo/webdnn#509]
First off, thanks for the awesome repo 😅, 本当に役に立てそうです.

I was wondering, have you considered adding reinforcement learning options to this repo as well?
What would it take to add options like that?

I imagine that might be a bit different from using pre-trained models, so maybe this would be out of scope here...

Otherwise, if you'd know other repos like that as good as yours, that would be interesting too!

**Comment by milhidaka** [comment]
WebDNN is designed to perform only inference step of DNN. Therefore, it is impossible to perform reinforcement learning.

However, users may train DNN-based agents with other frameworks like [ChainerRL](https://github.com/chainer/chainerrl), and convert the agents for WebDNN.

**Comment by tycho01** [comment]
Thank you for that, guess I'll close this then!
