### ISSUE TITLE
Output values become NaN on NVIDIA GPU with WebGPU

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#510]
One user reported that generating an image with NVIDIA GPU will bring large chunks of black space in the background. 
https://github.com/makegirlsmoe/makegirls.moe_web/issues/20

After our investigation, we find that some values become NULL in the model output...
![](http://i.imgur.com/PpDylYA.png)
Full output: https://drive.google.com/file/d/0Bx_f0Ep2RFzhV2dIUjZPOVZEWHc/view?usp=sharing

Edit: Sorry for confusing, it seems that output values are NaN, and those values become null after 
the json conversion... 
Edit2: I suspect NaN comes from the batch normalization operation, it seems that NVIDIA GPUs have some precision problems with WebGPU.  (After some investigations, we find the issue is not caused by tanh)

**Comment by Kiikurage** [comment]
Thank you for your report and sorry for late reply. we cannot reproduce that bug because we don't have OSX + NVIDIA environment. Please give us some time to fix this bug.

**Comment by zhangjk95** [comment]
The problem is solved in https://github.com/mil-tokyo/webdnn/commit/82840487dc357b1708573d61e9ebf3b54389e891. Thanks!
