### ISSUE TITLE
Numerical Problem in WebGL Backend

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#525]
I try to run our model with WebGL backend but I find that the result is wrong.
![](http://i.imgur.com/0Idy1BN.png)

Our generator model looks like
![](http://i.imgur.com/BNpMofC.png)

I try to print calculation results from both WASM and WebGL backends.
![](http://i.imgur.com/m9zPkWu.png)

I find that two vectors(64 * 128 * 128 feature maps) only differ 0.08 in total before the last conv layer, but after the last conv layer, the total difference becomes 54474...

I upload some debug files [here](https://drive.google.com/file/d/0Bx_f0Ep2RFzhb25zd0ZPNzhjU2s/view?usp=sharing)
model_before_last_conv is our model without the last conv layer(also without tanh)
model_after_last_conv is our model with the last conv layer(without tanh)
model_last_conv only contains the last conv layer, I do not know how to debug it independently

Let me know if you need any further information

**Comment by Kiikurage** [comment]
> but after the last conv layer, the total difference becomes 54474
Let me check that this result is about output from conv layer, without tanh?

Because "tanh" function is not natively supported in WebGL1 (=GLSL1.0), we implemented it [by using `exp`](https://github.com/mil-tokyo/webdnn/blob/5fd1573e1d624a0dcefc9bc85d5f97d361b99efe/src/graph_transpiler/webdnn/backend/webgl/kernels/tanh.py), this causes a large error. 

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/tanh.xhtml

**Comment by Aixile** [comment]
Yes. The result is before the tanh layer. The file asm_last_conv.json and gl_last_conv.json uploaded above is the output of the last conv layer for two backends.
I try to apply the tanh function manually in numpy.
![](http://i.imgur.com/PUbLJk9.png)
The result shows that the problem is caused by last conv layer not the tanh layer

**Comment by Kiikurage** [comment]
Thank you! I'll investigate more.

**Comment by Kiikurage** [comment]
In #524, i fixed the bug. It was caused by low precision of integer in GLSL. Integer precision in GLSL is not enough for large tensor computation such as generative CNN model's last output. Now i improved computation logic to handle such a large tensor. Please retry with latest revision!

**Comment by Aixile** [comment]
Thanks, I update our model and it works perfectly on Chrome. 
But I encounter problems on other browsers.
On Firefox, the result is blank.
![](http://i.imgur.com/8oGfkQX.png)

**Comment by Aixile** [comment]
My environment is macOS 10.12.4 + Firefox 54.0.1
[Demo testing url](http://maketest.girls.moe)
[Demo repo](https://github.com/makegirlsmoe/makegirls.moe_web/tree/webgl_test2)

**Comment by Aixile** [comment]
Sorry, I find this is because firefox disable WebGL by default...

**Comment by Kiikurage** [comment]
Do you see any warning from WebDNN about WebGL is disabled? or, WebDNN failed to handle some edge case, and it should be fixed.

**Comment by Kiikurage** [comment]
http://maketest.girls.moe/#/ works well in my Environment, macOS 10.12 + FF 55.0.3 !.

**Comment by Aixile** [comment]
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.24.45
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
FBO Texture Target: TEXTURE_2D
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[詳細]  inflate.min.js:15:724
Model loading failed for webassembly backend. Trying next backend: JSON.parse: unexpected character at line 1 column 1 of the JSON data  webdnn.es5.js:3766:21
XUL ノードのコンテンツドキュメントへの読み込みは推奨されません。この関数は間もなく削除されます。  jquery-3.1.1.min.js:3:17260
Error during service worker registration: DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: http://maketest.girls.moe/static/js/main.276cab4c.js:1]  main.276cab4c.js:1:514592
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed Sep 13 2017 00:30:20 GMT+0900 (JST)
Full Message: TypeError: this._extraPools is null
Full Stack: addActorPool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1510:5
get threadLifetimePool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:491:7
source@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:173:5
_createSourceMappedActors/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:363:20
_createSourceMappedActors/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:362:18
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:742:11
  main.js:1510
Array [ 0.3353168025634973, 0.08435705242287307, 0.9303896143559703, -0.8916092980954616, -1.1050212872960894, -0.8171278431677119, 1.0291237728200104, 0.5214037091280311, 0.8875313486102195, 0.12025728935070587, 他 152 個... ]  main.276cab4c.js:1:517508
Error: WebGL warning: texImage2D: Requested size at this level is unsupported.  webdnn.es5.js:1546:9
Error: WebGL warning: drawArrays: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0's image is not defined  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer must be complete.  webdnn.es5.js:2207:25
Error: WebGL warning: texImage2D: Requested size at this level is unsupported.  webdnn.es5.js:1546:9
Error: WebGL warning: drawArrays: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0's image is not defined  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer must be complete.  webdnn.es5.js:2207:25
Error: WebGL warning: texImage2D: Requested size at this level is unsupported.  webdnn.es5.js:1546:9
Error: WebGL warning: texSubImage2D: The specified TexImage has not yet been specified.  webdnn.es5.js:1372:17
Array [ 0.4692990032685608, -0.37992612952759913, 1.890922364719461, -0.5563399120707929, 0.5183055147661648, 0.682610631577576, 1.8631541710049757, -0.5661618036023277, -1.7874229259570293, 2.295392742800457, 他 152 個... ]  main.276cab4c.js:1:517508
Error: WebGL warning: drawArrays: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0's image is not defined  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer must be complete.  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0's image is not defined  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer must be complete.  webdnn.es5.js:2207:25
Array [ 0.41763534448068407, 1.0601573585874309, -0.5293192353678, 0.584804945717899, -0.2115392493320336, 0.19917060741882855, -0.1563043844955474, -0.992963910667227, -0.3528864984172264, 0.3139072085926003, 他 152 個... ]  main.276cab4c.js:1:517508
Error: WebGL warning: drawArrays: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0's image is not defined  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer must be complete.  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0's image is not defined  webdnn.es5.js:2207:25
Error: WebGL warning: drawArrays: Framebuffer must be complete.  webdnn.es5.js:2207:25
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.24.45
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
FBO Texture Target: TEXTURE_2D

**Comment by Aixile** [comment]
The operation is insecure. What should I do to allow this operation? I have already set webgl.force-enabled to true in about:config

**Comment by Kiikurage** [comment]
OK, i understand why the app doesn't work. The size  of tensor is too larger than what your GPU supports. My GPU, Intel Iris Graphics 6100, may be able to handle such a large tensor. Please give me some time to fix this problem.

**Comment by Kiikurage** [comment]
If you could, please run follow code snippet and tell me the result? this code reports the max supported texture size.

 `(gl = document.createElement('canvas').getContext('webgl')).getParameter(gl.MAX_TEXTURE_SIZE)`

**Comment by Aixile** [comment]
@Kiikurage 4096 on Firefox and 16384 on Chrome

**Comment by Kiikurage** [comment]
Thank you! I misunderstand that all browsers executed on same device report same value...

**Comment by Aixile** [comment]
Some users report that only half of the picture is generated on WebGL backend, although their devices have a MAX_TEXTURE_SIZE of 16384.
https://github.com/makegirlsmoe/makegirls.moe_web/issues/23
After some investigation, I reproduce the bug on both Firefox and Chrome with Windows 10 (i3 3220, no extra graphics card, but the bug disappeared on Ubuntu 16.04 with the same machine)
I find that the problem is caused by im2col operation before the gemm operation of the last conv layer.
The output of im2col is a 84934656-dim array, but the latter half of its value becomes 0.

**Comment by Kiikurage** [comment]
Thanks for your report and sorry for inconvinience. Now I work to support large tensor in devices which supports only small textures. Please give me a few days.

**Comment by Aixile** [comment]
Thank you for the great work!
I update to the lastest WebDNN. Now, the WebGL model works on both 4096 and 16384 devices. 
But I find there exist noisy rectangle patterns on generated images.
 ![](https://i.imgur.com/dkRtijD.png)

This phenomenon happens on both 4096 and 16384 devices.

[Demo URL](http://maketest.girls.moe)
[Repo Branch](https://github.com/makegirlsmoe/makegirlsmoe_web/tree/webgl_debug)

I am glad to help if you need more information.

**Comment by Kiikurage** [comment]
Maybe the noise appeared on the edge of the sub matrices (For support MAX_TEXTURE_SIZE=4096  devices, WebDNN automatically split large matrix into small sub matrices), but i have no idea why they appeared.

Please compile your model with `DEBUG=1 WEBGL_OPTIMIZE_TEXTURE_SIZE=0` options. By this options, original (not split) computation graph is visualized in `cg.dot` file. Can you share it with me?

**Comment by Aixile** [comment]
I upload the cg.dot along with our model and conversion script [here](https://drive.google.com/open?id=0Bx_f0Ep2RFzhMElFY2s1UXdPazQ).
You can compile the model by `python webdnn_conversion -l mgm.1.0.0.npz`.
Only chainer>=2.0.0 is required

**Comment by Kiikurage** [comment]
Thanks for sharing original model! I've downloaded it.

**Comment by Aixile** [comment]
I apologize that for some concerns we do not make the original model public available, but I am glad to provide our model for the development of your awesome library.

**Comment by Kiikurage** [comment]
Hi.
In latest revision, i fixed the numerical problem of WebGL. In my Android7 mobile phone, your model works fine.
<img width="1388" alt="screen shot 2017-11-20 at 19 59 15" src="https://user-images.githubusercontent.com/3253117/33026279-6e5cc226-ce53-11e7-9829-6fffa95e1042.png">

**Comment by Aixile** [comment]
@Kiikurage Thank you for your help, we have updated the site with the latest WebDNN!
