### ISSUE TITLE
For iOS simulators, WebDNN shows WebGPU is disabled although it is enabled 

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#565]
I run an iOS simulator with iOS 11/ iPhone 7 on Xcode.
Despite I have turned on the WebGPU, https://mil-tokyo.github.io/webdnn/ still shows webgpu is disabled.
![](https://i.imgur.com/JwOKH5d.png)

**Comment by Kiikurage** [comment]
AFAIK, iOS simulator doesn't support Metal. Therefore, even if the WebGPU option is displayed, it's not actually supported, I think.

**Comment by Aixile** [comment]
Thanks!
