### ISSUE TITLE
How can I specify the order of fallback of backend?

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#587]
When my app is executed on Chrome, WebDNN fallbacks webassembly rather then webgl as backend.
It may be specification of WebDNN, but I want to try webgl.
How can I specify the backend or the order of fallback of backend?

**Comment by Kiikurage** [comment]
Use `initOption.backendOrder` parameter in `WebDNN.load` like follows,

```js
// ex1
let runner = await WebDNN.load('./model', {
  backendOrder: ['webgl', 'webassembly'] // try WebGL first, and if it failed, then try WASM
});
```

```js
// ex2
let runner = await WebDNN.load('./model', {
  backendOrder: 'webgl' // forcibly use WebGL backend (if it's unavailable, an error is thrown)
});
```


https://mil-tokyo.github.io/webdnn/docs/api_reference/descriptor-runner/modules/webdnn.html#load

https://mil-tokyo.github.io/webdnn/docs/api_reference/descriptor-runner/interfaces/webdnn.initoption.html#backendorder

**Comment by y-ich** [comment]
Thank you and sorry for bothering you about documented one.
