### ISSUE TITLE
A softmax layer outputs a distribution with negative values on webgl backend.

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#588]
Thanks for your cooperations, I succeeded to run my model on webgl backend.
But on webgl backend, a softmax layer (probability distribution) outputs a distribution with negative values.
On other backends, there are no problems.

If you need a reproduction model, please let me know.
(The model is the one that I provided you with previously for performance issue on old Mac.)

**Comment by Kiikurage** [comment]
Sorry for confusing you about undocumented things, but softmax is currently not supported in WebGL backend (please see [#561](https://github.com/mil-tokyo/webdnn/issues/561#issuecomment-330409312)). Therefore you have to apply softmax in JavaScript like follows:

```js
y = runner.getOutputViews()[0].toActual();

function softMaxCPU(vec) {
  let max = vec.reduce((max, v) => Math.max(max, v))
  
  let expDelta = vec.map(v => Math.exp(v - max));
  let sumExpDelta = expDelta.reduce((sum, e) => sum + e);
  let result = expDelta.map(e => e / sumExpDelta);

  return result;
}

softMaxCPU(y);
```

**Comment by y-ich** [comment]
Now it works!
Thank you !
