### ISSUE TITLE
Requesting support for speed-optimized networks

### ISSUE THREAD

**Issue by kylemcdonald** [mil-tokyo/webdnn#589]
I've been experimenting more with webdnn, and I've found a small resnet style architecture that works well for my application. The parameters are small, it's quick to load, and fast to execute. But I'm trying to find a way to get more power out of the same number of parameters and in the same execution time. So I tried training a [MobileNet](https://github.com/fchollet/keras/blob/master/keras/applications/mobilenet.py) and [SqueezeNet](https://github.com/rcmalli/keras-squeezenet/blob/master/keras_squeezenet/squeezenet.py) on my task.

Unfortunately, it looks like they each have some layers that are not supported by WebDNN, or at least they are not supported by the WebGL backend. MobileNet has the relu6 (`K.relu(x, max_value=6)`) and `DepthwiseConv2D` layers. SqueezeNet uses built-in Keras layers, but I think the `concatenate` operation is not supported:

```
NotImplementedError: [WebGLDescriptorGenerator] Operator <Concat inputs={'x0': <Variable Variable157 shape=(1, 11, 11, 64), order=[N, H, W, C]>, 'x1': <Variable Variable158 shape=(1, 11, 11, 64), order=[N, H, W, C]>}, outputs={'y': <Variable Variable159 shape=(1, 11, 11, 128), order=[N, H, W, C]>}> is not handled by any generator handler
```

These kind of networks seem perfect target for WebDNN. Is there any possibility of adding support in the future?

**Comment by Kiikurage** [comment]
Now, we are implementing concatenation operator in WebGL backend. Maybe i'll add this feature in this week. Please give us some time.

**Comment by Kiikurage** [comment]
FYI: I add [SqueezeNet example](https://github.com/mil-tokyo/webdnn/tree/master/example/squeeze_net). Please check it.
