### ISSUE TITLE
Converting keras-frcnn model

### ISSUE THREAD

**Issue by nikhilaravi** [mil-tokyo/webdnn#592]
I would like to convert the [keras-frcnn model](https://github.com/yhenon/keras-frcnn) to run with webdnn, specifically the test_frcnn.py file. The output should be images which have bounding boxes for objects which have been recognized.

Would someone be able to guide me through how to transform the model to run with Webdnn?

**Comment by Kiikurage** [comment]
I read the original keras-frcnn source code. They inplemented ROI-pooling [as custom keras layer](https://github.com/yhenon/keras-frcnn/blob/master/keras_frcnn/RoiPoolingConv.py). To convert it, you need to [implement custom convert handler by yourself](https://mil-tokyo.github.io/webdnn/docs/tutorial/custom_operator/index.html).

**Comment by Kiikurage** [comment]
Staled.
