### ISSUE TITLE
AssertionError: [operator.replace_output(v_old, v_new)] 

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#595]
This error happens when I try to convert our model to the WebGL model. 

> Generator model loaded
> Start Convert
> [DEBUG] [OptimizeRule] apply: InsertTranspose
> [DEBUG] [OptimizeRule] apply: ReplaceConvolutionByIm2Col
> [DEBUG] [OptimizeRule] apply: ReplaceLinearBySgemm
> [DEBUG] [OptimizeRule] apply: FixSGEMMTextureShape
> [DEBUG] [OptimizeRule] apply: CheckTextureSize
> [DEBUG] -------------------------------------------------
> [DEBUG] <Variable Variable3 shape=(162, 16384), order=[C, N]>
> [DEBUG]   texture shape: (height=162, width=16384)
> [DEBUG]   original order: [C, N]
> [DEBUG]   original shape: (162, 16384)
> [DEBUG] 
> [DEBUG]   split axis: <Axis N>
> [DEBUG] 
> [DEBUG]   related operators:
> [DEBUG]   <Sgemm inputs={'A': <Variable Variable1 shape=(1, 162), order=[N, C]>, 'B': <Variable Variable3 shape=(162, 16384), order=[C, N]>}, outputs={'C': <Variable Variable4 shape=(1, 16384), order=[N, C]>}>
> [DEBUG]   <Transpose inputs={'x0': <Variable Variable2 shape=(16384, 162), order=[N, C]>}, outputs={'y': <Variable Variable3 shape=(162, 16384), order=[C, N]>}>
> [DEBUG] 
> Traceback (most recent call last):
>   File "webdnn_conversion.py", line 47, in <module>
>     exec_info = generate_descriptor("webgl", graph)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/interface/generator.py", line 102, in generate_descriptor
>     return generator(graph, **kwargs)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgl/generator.py", line 89, in generate
>     return WebGLDescriptorGenerator.generate(graph, **kwargs)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgl/generator.py", line 41, in generate
>     graph, _ = WebGLOptimizeRule().optimize(graph)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/optimize_rule.py", line 91, in optimize
>     graph, flag_changed = sub_rule.optimize(graph)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/optimize_rule.py", line 91, in optimize
>     graph, flag_changed = sub_rule.optimize(graph)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/optimize_rule.py", line 91, in optimize
>     graph, flag_changed = sub_rule.optimize(graph)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgl/optimize_rules/split_texture/split_variable.py", line 40, in optimize
>     _split_axis(v, axis, graph)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgl/optimize_rules/split_texture/split_variable.py", line 89, in _split_axis
>     _split_tensorwise(graph, op, v, [v1, v2], axis)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgl/optimize_rules/split_texture/split_variable.py", line 949, in _split_tensorwise
>     OptimizeRule.replace_variable(graph, op_0.outputs[key], v_pair[0])
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/optimize_rule.py", line 16, in replace_variable
>     old_var.replace(new_var, with_assert=with_assert)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/variable.py", line 133, in replace
>     self.output_from.replace_output(self, new_variable, with_assert=with_assert)
>   File "/Users/aixile/anaconda3/envs/py36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/operator.py", line 166, in replace_output
>     f"actual: v_old.order = {v_old.order}, v_new.order = {v_new.order}"
> AssertionError: [operator.replace_output(v_old, v_new)] v_old and v_new must be same data order.actual: v_old.order = [N, C], v_new.order = [C, N]

An extra question:
I set `os.environ["OPTIMIZE"] = "0"` but it seems that OptimizeRule is still applied according to the debug log.

**Comment by Kiikurage** [comment]
Some optimize rules such as replacing convolution into Im2Col and SGEMM is applied even if `OPTIMIZE==0` because it's needed to convert model. It probably should be changed more general name (ex. _Pass_ in LLVM).

The main question is just a bit bug, sorry. I'll fix it soon.

**Comment by Kiikurage** [comment]
OK, I've fixed the bug. Please retry.

**Comment by Aixile** [comment]
Confirmed, Thank you!
