### ISSUE TITLE
ONNX support

### ISSUE THREAD

**Issue by predict-r** [mil-tokyo/webdnn#606]
Maybe ONNX support would be a good idea. It is an open source format to represent Caffe2 and  PyTorch models. It is created by Facebook and Microsoft.

Here is someone working on transferring ONNX to Tensorflow. 
* https://github.com/onnx/onnx/issues/70 (user is fmassa )

Readings:

* https://research.fb.com/facebook-and-microsoft-introduce-new-open-ecosystem-for-interchangeable-ai-frameworks/
* https://github.com/onnx
* https://onnx.ai/

Is it possible?

**Comment by Kiikurage** [comment]
Yeah, that's a good idea! Previously, it was difficult to analyze the PyTorch model, so we abandoned to support PyTorch. We think that this problem will be solved by supporting ONNX. We'll do it later. Thanks.

**Comment by predict-r** [comment]
Cool! 👍

**Comment by Kiikurage** [comment]
I've implemented `ONNXConverter()` and `PyTorchConverter()` using ONNX. 
https://mil-tokyo.github.io/webdnn/docs/tutorial/pytorch.html
