### ISSUE TITLE
fallback is not easy to debugging in Chrome.

### ISSUE THREAD

**Issue by lygstate** [mil-tokyo/webdnn#659]
I have a patch for improve the condition.

**Comment by Kiikurage** [comment]
At the beginning of development of WebDNN, we implemented a fallback backend and easily checked whether the WebDNN graph compiler works properly. Now, not only fallback backend but also other backends such as WASM and WebGL are well-equipped. Therefore, the fallback backend is no longer necessary and we plan to delete it in the future.

However, as you said, whatever backends in current version of WebDNN, it is difficult to debug the calculation results on the browser. So I hope you will send the patch.

**Comment by lygstate** [comment]
@Kiikurage I've created a pull request, please take a look.
For now, once you running the fallback network, you can setting a breakpoint in the kernels_fallback.js file
In the Chrome browser.

**Comment by Kiikurage** [comment]
I merged your pull request. Thanks!
