### ISSUE TITLE
Flattenの必要性判定

### ISSUE THREAD

**Issue by Kiikurage** [mil-tokyo/webdnn#68]
次のいずれかの場合、Flattenは省略できる
- データオーダーが変化しない
- 変化はするが、軸サイズが1なため実質変化しない

この場合

```
X --[Flatten]--> Y
```

について、

- `Flatten` に `Nonsense` 属性をつけておき、カーネル生成時にスキップする
- `Y` をXと同じ場所にAllocateする

**Comment by milhidaka** [comment]
ChainerはデータオーダがNCHW, KerasはNHWCである。convの実装はNHWCを前提としており、データオーダを変更することがある。
H=W=1以外の場合、flattenが本当にnopなのかどうかがconverterでは決定できない。

**Comment by milhidaka** [comment]
assertion kills non-nop
