### ISSUE TITLE
Does WebDNN suport various resolutions image inputs like FCN

### ISSUE THREAD

**Issue by dhgrs** [mil-tokyo/webdnn#685]
Hi, 
I want to try style transfer by FCN(Fully Convolutional Network). FCN corresponds to various resolution image. Can I build that network by WebDNN?

And, are there some examples for style transfer(not for video but image)?

**Comment by Kiikurage** [comment]
WebDNN supports dynamic tensor shapes, but currently `ChainerConverter` supports conversion to only static computation graph. You have to define the computation graph with dynamic tensor shapes in WebDNN IR by hand.
We'll release the feature of automatic conversion to the computation graph with dynamic tensor shape. Please wait a few days.

**Comment by dhgrs** [comment]
Thanks for reply! I'm waiting for the release.

**Comment by Kiikurage** [comment]
Hi. 

I've implemented the placeholder feature for Chainer, and publish [sample project](https://github.com/Kiikurage/neural-style-transfer-webdnn). Please check it.

**Comment by dhgrs** [comment]
I checked the sample and could build computation graph with dynamic tensor shapes. It's wonderful!
Thanks!
