### ISSUE TITLE
API page not scrollable on FF

### ISSUE THREAD

**Issue by fuzzthink** [mil-tokyo/webdnn#686]
Use FF 57 on ubuntu 16.04. https://mil-tokyo.github.io/webdnn/docs/api_reference/descriptor-runner/index.html is not scrollable. Anyone else see same issue?

**Comment by Kiikurage** [comment]
Sorry, I'll fix it soon.

**Comment by fuzzthink** [comment]
https://mil-tokyo.github.io/webdnn/docs/api_reference/descriptor-runner/modules/*.html are not scrollable too. Scrolls fine in Chrome.

**Comment by milhidaka** [comment]
Fixed in #698 .
