### ISSUE TITLE
Is it hard to support different size padding?

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#687]
Hi.

My Keras model is using AveragePooling2D(pool_size=(2, 2), padding="same") and it causes the error of "[KerasConverter] Currently WebDNN doesn't supports different size padding".

I also tried ZeroPadding2D(padding=((0,1),(0,1))) before AveragePooling2D but it was same thing.

If you know any manners to avoid this error, please let me know.
Thank you!

**Comment by Kiikurage** [comment]
it's required to modify current implementation of converter handler, but very easy, I think (The implementation I considered is very similar to `tf.Pad`).

**Comment by Kiikurage** [comment]
Hi.

I implemented uneven-size padding like your case in #691.

**Comment by y-ich** [comment]
I updated WebDNN and finally I succeeded to convert my model!

I really appreciate you.
Thank you for your wonderful framework!
