### ISSUE TITLE
Behaviors between Keras Dense and WebDNN Dense are different when 0D input.

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#693]
On Keras,

    tensor = ... # multi-channel scalar, or tensor.shape = (?, n) where n > 1
    Dense(1)(tensor) # outputs scalar

On WebDNN converting the above model,

    tensor = ... # multi-channel scalar, or tensor.shape = (?, n) where n > 1
    Dense(1)(tensor) # outputs n-length vector

**Comment by Kiikurage** [comment]
Can you give me the code to reproduce the result?

**Comment by y-ich** [comment]
I am sorry, I misunderstood the problem.
