### ISSUE TITLE
[Benchmark] KerasJS version change, script not update, encoder.py file path changed

### ISSUE THREAD

**Issue by zhaoming0** [mil-tokyo/webdnn#725]
[KerasJS version](https://github.com/mil-tokyo/webdnn/blob/master/example/benchmark/README.md#version) was updated to `a43f7a5a348e45f7a525e19952e232b123d85af1` in PR #712, but script  [`convert.sh`](https://github.com/mil-tokyo/webdnn/blob/master/example/benchmark/convert.sh) wasn't updated the relative version information.

[line13:](https://github.com/mil-tokyo/webdnn/blob/master/example/benchmark/convert.sh#L13) git reset --hard a43f7a5a348e45f7a525e19952e232b123d85af1
[line16:](https://github.com/mil-tokyo/webdnn/blob/master/example/benchmark/convert.sh#L16) `encoder.py` file has been change `python3 ./python/encoder.py ../output/kerasjs/resnet50/model.h5`

**Comment by zhaoming0** [comment]
@Kiikurage PTAL

**Comment by Kiikurage** [comment]
Solved in #726
