### ISSUE TITLE
[Benchmark] Error `path to protobuf-serialized model definition file is missing.` happened with KerasJS

### ISSUE THREAD

**Issue by zhaoming0** [mil-tokyo/webdnn#731]
When testing benchmark with [KerasJS Version a43f7a5](https://github.com/mil-tokyo/webdnn/blob/master/example/benchmark/README.md#version) of ResNet50/VGG16/InceptionV3 models using latest code following this [README](https://github.com/mil-tokyo/webdnn/blob/master/example/benchmark/README.md#how-to-run) 

it throws error:
```[Model] path to protobuf-serialized model definition file is missing.```
  
 
  
Detail info as below:
```
Benchmark
	
	Environment Information
		   UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
		    Platform: MacIntel
	
	Configuration
		   framework: keras.js
		        name: keras.js (CPU)
		   modelName: resnet50
		   batchSize: 1
		   iteration: 4
		         gpu: false
	
	Run
		[Model] path to protobuf-serialized model definition file is missing.
```

**Comment by Kiikurage** [comment]
I fixed this error due to obsolete API usage of KerasJS.

**Comment by hmhwe** [comment]
Did you fix the error?

**Comment by hellc3c** [comment]
how to fix, I met the same problem. I will very appreciate if you can give me an answer.
