### ISSUE TITLE
how to import webdnn in react

### ISSUE THREAD

**Issue by akshay951228** [mil-tokyo/webdnn#733]
error while importing "import * as WebDNN from "./dist/webdnn""
![screenshot from 2018-01-13 15-24-53](https://user-images.githubusercontent.com/25878082/34904973-051e4c9c-f876-11e7-9ef7-0e1d027f5837.png)
how to solve this

**Comment by fuzzthink** [comment]
There are a few problems and bugs.

1. the JS API instruction of `import * as WebDNN from "webdnn"` is wrong, and needs to be fixed as webdnn is not available as npm package - #666 . 
You seem to noticed and correctly changed the path.

2. Most of the not defined errors goes away if you use Babel and add 'pathToWebdnn/**' to its exclude option.

3. For some reason, `WebDNN.load` will give error saying `load` is not exported by webdnn. It is, so have no clue why. This fixed it for me and got it to work:

Edit webdnn.js:
remove top few lines up to until 'use strict'; 
remove of file bottom closing functions line: 
`})));`

These removed wrappers makes it work via html script, but won't work as documented in JS API. Tried the es5 version, no difference in terms of errors stated above.

Unless someone has a good solution (no messy babel settings) to make it work, it may be a good idea to publish a version w/o the wrappers as suggested, o/w it doesn't seem to work w/o html script.

**Comment by akshay951228** [comment]
It works for me 
What I did is
copy the webdnn.es5.js into the src directory 
and then added line this **/*eslint-disable */** on top in the webdnn.es5.js file
as I was imported as Like in **import * as WebDNN from "./webdnn.es5"**

**Comment by fuzzthink** [comment]
Hmm, that didn't work for me, it still complain `load` not exported.

**Comment by akshay951228** [comment]
@fuzzthink have put /*eslint-disable */  on top of webdnn.es5.js  which is located at dist folder
it won't work on webdnn.es5.js

**Comment by fuzzthink** [comment]
@akshay951228 Yes, I put that in webdnn.es5.js located in dist folder. That's the only place the file exists, so not sure what your second sentence mean. Can you let me know your build setup? Here's plugins of my rollup:

```
    plugins: [
      replace({
        'process.env.NODE_ENV': JSON.stringify('development') // needed for fb's emptyObject.js
      }),
      resolve({ // resolve non-es modules
        browser: true
      }),
      babel({
        babelrc: false,
        exclude: ['node_modules/**', 'dist/**'], // exclude dist to fix 'load' not exported by webdnn
        plugins: [
          '@babel/plugin-proposal-object-rest-spread',
          '@babel/plugin-transform-react-jsx',
        ]
      }),
      commonjs(),
  ]
```

**Comment by akshay951228** [comment]
my dir struct 
![webdnn](https://user-images.githubusercontent.com/25878082/35191153-4c1b3f32-fe99-11e7-8e0b-4106f19033c0.png)
In App.js I imported like this **import * as WebDNN from "./webdnn.es5"**

It's work for me
