### ISSUE TITLE
Ability to support quantized model

### ISSUE THREAD

**Issue by fuzzthink** [mil-tokyo/webdnn#742]
It would be very useful to add support for loading quantized model such as bin files produced by keras.js' encoder.py, which cuts a model down by 4x. This is useful since non trivial models are huge and making clients download say 10MB vs 40MB makes a huge difference.

**Comment by milhidaka** [comment]
WebDNN has similar ability to compress weight to 1/4~1/5.
It can be enabled by passing `constant_encoder_name="eightbit"` to `generate_descriptor`.
For example, passing `--encoding=eightbit` argument to https://github.com/mil-tokyo/webdnn/blob/991172ba94b714b9d84b71b32b6f961ef2d73121/example/resnet/convert_resnet_keras.py does it.
