### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by iver56** [mil-tokyo/webdnn#750]
```
$ npm install github:mil-tokyo/webdnn
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\WebDNN\docs\template\typedoc\plugin" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Iver\AppData\Roaming\npm-cache\_logs\2018-01-25T09_40_58_172Z-debug.log
```

Environment:
* Git Bash, Windows 10
* node v8.9.4
* npm 5.6.0

Relevant package.json documentation on local paths:
https://docs.npmjs.com/files/package.json#local-paths

**Comment by milhidaka** [comment]
Currently installing WebDNN with npm is not supported.
Please use `dist/webdnn.js` for now.
I'm planning to support npm in near future.

**Comment by iver56** [comment]
Thanks, I'm looking forward to the npm support 👍

**Comment by milhidaka** [comment]
We supported to install WebDNN with npm.
Please use `npm install webdnn`.
Also, working example is here. https://github.com/milhidaka/webdnn-exercise/tree/master/webpack
