### ISSUE TITLE
Are there any ways to adopt tensorflow algorithm for padding="same"?

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#786]
Hi.

As described in #694, WebDNN and TensorFlow adopt different algorithms on the boundary for padding="same".
Are there any ways to use the algorithm of TensorFlow for padding="same"?

This project seems to have entered a rest. I hope that it will become active soon.
Thank you.

**Comment by milhidaka** [comment]
Currently there is no implementation.
We need a flag to indicate tensorflow style padding and gpu kernel implementation to accept it.
I can take time to support it several days later.

**Comment by milhidaka** [comment]
Now supported in master branch.
Note that uneven padding (left and right size is different) is still unsupported.

**Comment by y-ich** [comment]
@milhidaka Thank you!
