### ISSUE TITLE
[Question] Can I check how many inputs I can feed efficiently?

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#795]
Hi.

In my understanding, WebDNN model can be feeded several inputs at once if GPU has enough capacity. Is that right?

And if so, I want to know how many inputs I can feed efficiently on the target GPU.
Is it possible?

Thanks.

**Comment by milhidaka** [comment]
I assume "several inputs" means batch size.
It is difficult to know which batch size is efficient in advance.
You will need to benchmark on actual model and hardware.
WebDNN has "placeholder" feature, so changing batch size dynamically by javascript is possible.
However, there is no example nor document. Do you need it?

**Comment by y-ich** [comment]
I have thought that an input of WebDNN model is a placeholder, that accepts a batch.
Is it wrong? if wrong and I need an additional code to enable an input to be a placeholder, I need the docment.

And I have a related question.
Can I run several sessions of batch size=1 without waiting each end?
In that case, do any concurrent optimizations happen? Or it just put task jobs into a queue inside WebDNN?

If there are some optimizations, I may try benchmark of several sessions rather than batch size.

Thanks

**Comment by milhidaka** [comment]
> I have thought that an input of WebDNN model is a placeholder, that accepts a batch.
Your understanding is right.

You may run multiple sessions simultaneously, although it is not tested.
There is no optimization about multiple sessions. Throughput will be better with large batch compared to using several sessions.

**Comment by y-ich** [comment]
I see. Now I want to try large batch.
Could you give me an example or a document if it is not trivial?

**Comment by milhidaka** [comment]
Giving placeholder object to batch size will be enough.
If you have trouble, please reopen the issue.
I will add some placeholder examples later.

**Comment by y-ich** [comment]
Setting double-sized inputs into the first element of a return value of getInputViews caused the following error.

    symbolic_typed_array.js:165 Uncaught (in promise) RangeError: Source is too large
        at Float32Array.set (<anonymous>)
        at r.set (symbolic_typed_array.js:165)
        at NeuralNetwork.evaluate (neural_network.js:38) # NeuralNetwork is a class of my app.

Do I need to specify batch size when converting a model?

**Comment by milhidaka** [comment]
`setPlaceholderValue({label: value})` have to be called before `getInputViews()`.
https://github.com/mil-tokyo/webdnn/blob/5fbe0f13577d328984cb93982e75dc338c4dc818/src/descriptor_runner/descriptor_runner/descriptor_runner.ts#L157

**Comment by y-ich** [comment]
No changes... Maybe I misunderstand APIs^^;
I am looking forward to the examples.

**Comment by y-ich** [comment]
Hi.

(It seems that I have no permissions to reopen this issue)
Could you give me multiple-batch example?

I read this thread again, and I understood that first you need batch size placeholder explicitly in your model and setting it by setPlaceholderValue enables multiple batches. Is my understanding right?

My model seems to have no parameters for batch size. (it is TensorFlow model with [-1, H, W, C)].

A multiple-batch example (for TensorFlow frontend) will help me a lot.
Thank you.

**Comment by y-ich** [comment]
Sorry, I overlooked the argument batch_size of constructor for TensorFlowConverter.
Setting the argument to concrete value seems to work.
(Setting batch_size to None did not work for TensorFlowConverter.)

Thank you!
