### ISSUE TITLE
getImageArray doesn't handles ImageData type

### ISSUE THREAD

**Issue by marcorighini** [mil-tokyo/webdnn#838]
`getImageArrayFromDrawable` correctly calls `getImageArrayFromImageData` if input `drawable` is of type `ImageData`.

From the documentation seems that `getImageArray` should correctly handle a source of type `ImageData`. The problem is that if you provide `image` of type `ImageData` a `TypeError` exception is thrown instead of calling `getImageArrayFromDrawable`.

**Comment by milhidaka** [comment]
Fix merged to master branch. Please use latest `dist/webdnn.js`.
