### ISSUE TITLE
Weird package.json entry point

### ISSUE THREAD

**Issue by Kouty** [mil-tokyo/webdnn#844]
This is not a bug, just something I don't understand.

Inside WebDNN `package.json` file there is this entry point: ` "main": "src/descriptor_runner/webdnn.js"`.
That file is not present in the GitHub repository. At least not at that location.

When installing WebDNN using npm install in combination with Webpack, it works fine. In fact that file magically appears inside `node_modules` webdnn directory.

But when installing WebDNN with npm using a specific branch, `src/descriptor_runner/webdnn.js` doesn't exist, and Webpack fails to compile.

Shouldn't it be ` "main": "dist/webdnn.js"`?

**Comment by milhidaka** [comment]
When WebDNN is installed with npm, user will need to use webpack to resolve `require`.
If `package.json` points to `dist/webdnn.js`, it is already packed, so webpack for the whole user's project does not work as expected.
I think current setting is useful for ordinary user.

When user downloads WebDNN from github, `src/descriptor_runner/webdnn.js` can be built with `scripts/build.sh`.

**Comment by Kouty** [comment]
It seems to me that `scripts/build.sh` will create `dist/webdnn.js` not `src/descriptor_runner/webdnn.js`, but I may be wrong.
It also seems that `dist/webdnn.js` works properly with webpack require or import. Again I may be wrong.

Anyway since it is not a bug, I am going to close this issue tomorrow, if no other comment comes in.

**Comment by milhidaka** [comment]
I confirmed that `dist/webdnn.js` can be used as input to webpack.
I thought that one advantage to use `src/descriptor_runner/webdnn.js` is that source map of webdnn is output along with that of user code.
However, `await` is unrolled in source code level, so it is difficult to debug eventually.
Therefore, I will change the main module to `dist/webdnn.js` for simplicity.

**Comment by Kouty** [comment]
As you think it is better. In both cases there is a way to make it work properly inside webpack using npm.
