### ISSUE TITLE
 [convert_caffe] Failed generating descriptor for backend webgl: zero-size array to reduction operation maximum which has no identity when setting --encoding eightbit

### ISSUE THREAD

**Issue by seranus** [mil-tokyo/webdnn#846]
I'm trying to convert yolo face detection. Conversion seem to work but when setting eightbit I get an error

I run the converter with params --backend webgl --input_shape (1,3,448,448) --input_name data --output_names layer20-fc --encoding eightbit --out output face.caffemodel

caffe model is from here: https://github.com/abars/YoloKerasFaceDetection

**Comment by milhidaka** [comment]
The command worked for me in latest version.

The issue may be fixed in #825. Please try latest master branch or v1.2.5.

**Comment by seranus** [comment]
Thanks, it works now!

I got 3 different graph files as output for the same backend. Can you give me an explanation why is that so?

**Comment by milhidaka** [comment]
In WebGL backend, each variable in neural networks is represented as "texture" in WebGL.
Texture has size limit, and it depends on the hardware.
To support various hardware, webdnn may divide variables to several textures not to exceed the size limit.
Currently webdnn assumes three level of size limit, and generates graph descriptor for each limit.
`webdnn.js` detects hardware limit and loads the suitable one.

**Comment by seranus** [comment]
Thank you
