### ISSUE TITLE
getImageArray doesn't resize in case of ImageData input

### ISSUE THREAD

**Issue by marcorighini** [mil-tokyo/webdnn#849]
In case of an input of type `ImageData`, `getImageArray` doesn't takes into account `SourceRect & DestinationRect` in the `option` parameter.
This is due to an incomplete fix [https://github.com/mil-tokyo/webdnn/commit/d8dd11deee4d8a133f436084707f913df7f50324](https://github.com/mil-tokyo/webdnn/commit/d8dd11deee4d8a133f436084707f913df7f50324).
This fix enables `ImageData` as input type. The problem is due to `getImageArray` for `ImageData` that calls `getImageArrayFromDrawable`, that calls `getImageArrayFromImageData` without properly resampling before (correct handling is done instead for canvas by the method `getImageArrayFromCanvas`).

See pull request for a temporary fix #850

**Comment by milhidaka** [comment]
Fixed in #850
