### ISSUE TITLE
ONNX Support

### ISSUE THREAD

**Issue by jspisak** [mil-tokyo/webdnn#896]
HI WebDNN Team,
This looks like a great project and given it supports both PyTorch and Chainer, it likely supports the use of exported ONNX models from both projects. I have two questions:

1. Have you tested ONNX models from PyTorch (more near to my heart.. :))?

and

2. Are you interested to join the ecosystem of projects? see more at onnx.ai

**Comment by milhidaka** [comment]
WebDNN supports ONNX.
Actually, PyTorch converter is implemented by parsing exported ONNX model.
https://github.com/mil-tokyo/webdnn/tree/master/src/graph_transpiler/webdnn/frontend/onnx
I have not tested ONNX exported by Chainer, but it theorethically works.

As more frameworks are supporting ONNX, we will focus ONNX as primary input format in the future.

**Comment by jspisak** [comment]
thanks @milhidaka - this is cool to see. Let me know if you'd like to be showcased as an ONNX project on onnx.ai. If so, send me a email at jspisak@fb.com and we can add your logo, etc..
