### ISSUE TITLE
OpenNSFW caffe model always returns the same output

### ISSUE THREAD

**Issue by zaghaghi** [mil-tokyo/webdnn#909]
Hi,

I used `convert_caffe.py` to generate WebDNN computation graph from Yahoo open-nsfw caffe model.
```
python $WEBDNN/bin/convert_caffe.py  --input_name data --input_shape '(1,3,224,224)' --output_names fc_nsfw --out output  resnet_50_1by2_nsfw.caffemodel
```

The problem is that when I'm using the generated model in browser, the runner always returns same results no matter what image I use.

**Comment by milhidaka** [comment]
I found problems in caffe converter.
Could you try 909 branch (https://github.com/mil-tokyo/webdnn/tree/909)?
You may install it with
```
pip install git+https://github.com/mil-tokyo/webdnn.git@909
```

I am not familiar with OpenNSFW, but I can get different outputs from `example/data/{school_bus,dolphin}.jpg`. I used resnet50 example with only changing output display. ` --out output_chainer` is used for output directory.

**Comment by zaghaghi** [comment]
Hi milhidaka,

Thanks, it's working now.
Note that this patch not working with `chainer==1.23` and `chainer==2.0` because `chainer.links.BatchNormalization` object has no attribute `_dtype`.

**Comment by milhidaka** [comment]
Thanks for reporting. I will merge it to master.
Since chainer 2.0 is too old, I will stop supporting it.
